include:
  - remote: https://git-cdn.e15r.co/gitlab/ci/wordpress/-/raw/main/plugins/default.yml

# Plugin does not support 5.6 or 7.0.
PHPunit:PHP7.0:MySQL:
  rules:
    - if: true
      when: never

PHPunit:PHP5.6:MySQL:
  rules:
    - if: true
      when: never
